name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:  # Allows manual trigger

permissions: 
    contents: read
    pages: write
    id-token: write # Ensure proper token permissions


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json 

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
         npm run build
         echo "Build step completed"

      - name: Debug build folder
        run: ls -la build || echo "Build folder not found!"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages # Explicitly name the artifact
          path: build # Ensure correct path

      - name: List uploaded artifacts
        run: ls -la ${{ runner.temp }}/_github_workflow/artifacts || echo "No artifacts found!"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2